-- Sample Vendors Data
-- Insert 5 sample vendors for testing

-- School ID from existing data
-- school_id: 60da2256-81fc-4ca5-bf6b-467b8d371c61

-- Admin user ID for created_by
-- user_id: bed3ada7-ab32-4a74-84a0-75602181f553

-- Vendor 1: Food Service
INSERT INTO vendors (
    school_id,
    company_name,
    vendor_type,
    category,
    primary_contact_name,
    primary_contact_title,
    email,
    phone,
    website,
    address_line1,
    city,
    state,
    postal_code,
    description,
    services_provided,
    certifications,
    contract_start_date,
    contract_end_date,
    contract_value,
    payment_terms,
    status,
    performance_rating,
    preferred,
    created_by_id
) VALUES (
    '60da2256-81fc-4ca5-bf6b-467b8d371c61',
    'Fresh Foods Catering',
    'food_service',
    'cafeteria',
    'Maria Garcia',
    'Account Manager',
    'orders@freshfoods.com',
    '+1-555-0101',
    'https://www.freshfoods.com',
    '123 Food Street',
    'Springfield',
    'IL',
    '62701',
    'Full-service cafeteria management and catering for schools. Specializing in healthy, nutritious meals for students.',
    ARRAY['daily cafeteria service', 'event catering', 'vending machines', 'breakfast programs'],
    ARRAY['ServSafe Certified', 'USDA Food Safety', 'Organic Certified'],
    '2024-09-01',
    '2025-08-31',
    75000.00,
    'net_30',
    'active',
    4.75,
    TRUE,
    'bed3ada7-ab32-4a74-84a0-75602181f553'
);

-- Vendor 2: Office Supplies
INSERT INTO vendors (
    school_id,
    company_name,
    vendor_type,
    category,
    primary_contact_name,
    primary_contact_title,
    email,
    phone,
    website,
    address_line1,
    city,
    state,
    postal_code,
    description,
    services_provided,
    contract_start_date,
    contract_end_date,
    contract_value,
    payment_terms,
    status,
    performance_rating,
    preferred,
    created_by_id
) VALUES (
    '60da2256-81fc-4ca5-bf6b-467b8d371c61',
    'Office Supply Pro',
    'supplies',
    'office_supplies',
    'John Smith',
    'Education Sales Rep',
    'schools@officesupplypro.com',
    '+1-555-0202',
    'https://www.officesupplypro.com',
    '456 Supply Avenue',
    'Springfield',
    'IL',
    '62702',
    'Complete office and educational supplies. Bulk discounts for schools.',
    ARRAY['office supplies', 'classroom materials', 'technology accessories', 'furniture'],
    '2024-01-01',
    '2024-12-31',
    25000.00,
    'net_60',
    'active',
    4.50,
    TRUE,
    'bed3ada7-ab32-4a74-84a0-75602181f553'
);

-- Vendor 3: Maintenance Services
INSERT INTO vendors (
    school_id,
    company_name,
    vendor_type,
    category,
    primary_contact_name,
    primary_contact_title,
    email,
    phone,
    address_line1,
    city,
    state,
    postal_code,
    description,
    services_provided,
    certifications,
    contract_start_date,
    contract_end_date,
    contract_value,
    payment_terms,
    status,
    performance_rating,
    preferred,
    created_by_id
) VALUES (
    '60da2256-81fc-4ca5-bf6b-467b8d371c61',
    'Clean & Shine Services',
    'maintenance',
    'janitorial',
    'Robert Johnson',
    'Operations Manager',
    'contact@cleanshine.com',
    '+1-555-0303',
    '789 Clean Street',
    'Springfield',
    'IL',
    '62703',
    'Professional janitorial and maintenance services for educational facilities.',
    ARRAY['daily cleaning', 'floor maintenance', 'window washing', 'emergency cleanup'],
    ARRAY['Green Cleaning Certified', 'OSHA Compliant'],
    '2024-07-01',
    '2025-06-30',
    50000.00,
    'upon_completion',
    'active',
    4.25,
    FALSE,
    'bed3ada7-ab32-4a74-84a0-75602181f553'
);

-- Vendor 4: IT Services
INSERT INTO vendors (
    school_id,
    company_name,
    vendor_type,
    category,
    primary_contact_name,
    primary_contact_title,
    email,
    phone,
    website,
    address_line1,
    city,
    state,
    postal_code,
    description,
    services_provided,
    certifications,
    payment_terms,
    status,
    performance_rating,
    total_orders,
    created_by_id
) VALUES (
    '60da2256-81fc-4ca5-bf6b-467b8d371c61',
    'TechSupport Pro',
    'it_services',
    'it_support',
    'David Lee',
    'Technical Director',
    'help@techsupportpro.com',
    '+1-555-0404',
    'https://www.techsupportpro.com',
    '321 Tech Boulevard',
    'Springfield',
    'IL',
    '62704',
    'Comprehensive IT support and technology solutions for educational institutions.',
    ARRAY['network maintenance', 'helpdesk support', 'software licensing', 'hardware repair'],
    ARRAY['Microsoft Certified', 'CompTIA A+', 'Cisco Certified'],
    'net_30',
    'active',
    4.60,
    15,
    'bed3ada7-ab32-4a74-84a0-75602181f553'
);

-- Vendor 5: Transportation
INSERT INTO vendors (
    school_id,
    company_name,
    vendor_type,
    category,
    primary_contact_name,
    primary_contact_title,
    email,
    phone,
    address_line1,
    city,
    state,
    postal_code,
    description,
    services_provided,
    certifications,
    insurance_policy_number,
    insurance_expiry_date,
    contract_start_date,
    contract_end_date,
    contract_value,
    payment_terms,
    status,
    performance_rating,
    preferred,
    total_orders,
    created_by_id
) VALUES (
    '60da2256-81fc-4ca5-bf6b-467b8d371c61',
    'Yellow Bus Company',
    'transportation',
    'school_bus',
    'Sarah Williams',
    'Fleet Manager',
    'dispatch@yellowbus.com',
    '+1-555-0505',
    '654 Transport Way',
    'Springfield',
    'IL',
    '62705',
    'Safe and reliable school transportation services. Full fleet of modern, well-maintained buses.',
    ARRAY['daily bus routes', 'field trip transportation', 'after-school activities', 'special needs transport'],
    ARRAY['DOT Certified', 'School Bus Safety Certified'],
    'POL-12345678',
    '2025-12-31',
    '2024-09-01',
    '2025-08-31',
    120000.00,
    'net_30',
    'active',
    4.80,
    TRUE,
    8,
    'bed3ada7-ab32-4a74-84a0-75602181f553'
);

-- Success message
SELECT 'Sample vendor data inserted successfully!' as message;
